const stockProductos = [
    {
        id: 1,
        image: "./imagenes/auriculares.webp",
        title: "Auriculares",
        description: "Sonido envolvente",
        price: 500,
    },
    {
        id: 2,
        image: "./imagenes/auriculares.webp",
        title: "Auriculares 2",
        description: "Sonido envolvente",
        price: 600,
    },
    {
        id: 3,
        image: "./imagenes/auriculares.webp",
        title: "Auriculares 3",
        description: "Sonido envolvente",
        price: 700,
    },
    {
        id: 4,
        image: "./imagenes/auriculares.webp",
        title: "Auriculares 4",
        description: "Sonido envolvente",
        price: 800,
    },
    {
        id: 5,
        image: "./imagenes/auriculares.webp",
        title: "Auriculares 5",
        description: "Sonido envolvente",
        price: 900,
    },
    {
        id: 6,
        image: "./imagenes/auriculares.webp",
        title: "Auriculares 6",
        description: "Sonido envolvente",
        price: 1000,
    },
    {
        id: 7,
        image: "./imagenes/mouse.jpg",
        title: "Mouse",
        description: "Con cable usb",
        price: 500,
    },
    {
        id: 8,
        image: "./imagenes/mouse.jpg",
        title: "Mouse 2",
        description: "Con cable usb",
        price: 600,
    },
    {
        id: 9,
        image: "./imagenes/mouse.jpg",
        title: "Mouse 3",
        description: "Con cable usb",
        price: 700,
    },
    {
        id: 10,
        image: "./imagenes/mouse.jpg",
        title: "Mouse 4",
        description: "Con cable usb",
        price: 800,
    },
    {
        id: 11,
        image: "./imagenes/mouse.jpg",
        title: "Mouse 5",
        description: "Con cable usb",
        price: 900,
    },
    {
        id: 12,
        image: "./imagenes/mouse.jpg",
        title: "Mouse 6",
        description: "Con cable usb",
        price: 1000,
    },
    {
        id: 13,
        image: "./imagenes/teclado.webp",
        title: "Teclado",
        description: "Con luces y cables usb",
        price: 500,
    },
    {
        id: 14,
        image: "./imagenes/teclado.webp",
        title: "Teclado 2",
        description: "Con luces y cables usb",
        price: 600,
    },
    {
        id: 15,
        image: "./imagenes/teclado.webp",
        title: "Teclado 3",
        description: "Con luces y cables usb",
        price: 700,
    },
    {
        id: 16,
        image: "./imagenes/teclado.webp",
        title: "Teclado 4",
        description: "Con luces y cables usb",
        price: 800,
    },
    {
        id: 17,
        image: "./imagenes/teclado.webp",
        title: "Teclado 5",
        description: "Con luces y cables usb",
        price: 900,
    },
    {
        id: 18,
        image: "./imagenes/teclado.webp",
        title: "Teclado 6",
        description: "Con luces y cables usb",
        price: 1000,
    },
    



]